# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66fd33ae361f440ea961807a1862ba7d7e23e9c6c50e974cb3afbb19835a7ddf69e265b81e0863f273aa98881e0aea9809ac44632d1eaf66a34591aea602e595

test:
  secret_key_base: 6d23b16dafb35032067e743c50aa6b58249fe93ca1f9505c63f1febf71782bef94ec6b57c6c17ee5a81b6f315565c8b4b08ac2c7c7b3039c66952a5f133f4ecf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
